### ISSUE TITLE
Fails to sort out LOD levels, dumps everything to all LOD files instead of only LOD collections.

### ISSUE THREAD

**Issue by romandesign** [AsoboStudio/glTF-Blender-IO-MSFS#257] opened 2023-07-15 06:03 UTC
### Current Behavior

If you click "limit to selected objects" it works. Any other option creates identical LOD files (same file size!) with everything dumped into them. If "selected objects" is checked, and also "renderable objects" is checked - it works, no need to select an object, but uncheck "selected" and it doesn't work in any other way... All other limiting options result in identical LOD files. Also tested in 3.3.0LTS - same behaviour. Any file I tried. New one too. It's an exporter bug...

### Expected Behavior

Object_LOD00, Object_LOD01, Object_LOD02 collections should result in 3 LOD sets of files, and it was working before. With version 1.3.1 and Blender 3.3.8LTS (and I also tested a fresh install 3.3.0LTS) anything other than "limit to selected" dumps everything in 3 identical sets of files (same number of bytes).

### Steps To Reproduce

Create new file. Create collections named Object_LOD00, Object_LOD01, Object_LOD02, place different objects in each. Select LOD export by collections, refresh and make sure files are named properly. Select "limit by renderable" or any other limits other than "limit by selected" and observe 3 identical files. Re-import .glTF file to observe that all objects from all LOD collections are there.

### Environment

```markdown
- OS:Win11
- Blender: 3.3.8LTS
- glTF-Blender-IO-MSFS: 1.3.1
```

### Anything else?

Here are my setting - that do not work as they should:
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/9002820/0a241521-82d0-40e8-a702-2e06ca0a970b)
![image](https://github.com/AsoboStudio/glTF-Blender-IO-MSFS/assets/9002820/148f52d2-fc27-41b3-93a1-b5eeefa7982a)

**Comment by PhysicsTeacher1** [comment] 2023-07-15 19:32
I get the same results.  This is a show-stopper!
Will investigate further, but it makes 1.3.1 unusable for me.
These settings are really used directly by the Khronos code and are transferred there on export.  I'll look on my own later.
If I had to guess, since it works with Selected Objects and ignores other stuff that the problem is a problem in the setting transfer code.  Perhaps the Selected Objects should default to True, but that would make it unnecessary.
You note that when you exported previously that each LOD was selected one at a time.

**Comment by romandesign** [comment] 2023-07-15 20:20
Yes, it worked fine previously. But note that now I don't have to select anything either - the "selected object" checkbox doesn't work as intended, at least with "renderable" also selected. It just durns off this bug, so to speak. I don't have to select any objects - with everything deselected it still outputs full LODs properly, despite "selected objects" checked.

**Comment by PhysicsTeacher1** [comment] 2023-07-15 20:35
When you say "it worked fine previously", please indicate what version was "previously" for the exporter as well as for Blender.  I have an idea.  Thanks.

**Comment by romandesign** [comment] 2023-07-15 20:38
Unfortunately, I can't be 100% certain, but it was the last exporter version before current, and Blender 3.1, but I also tried Blender 3.1 with this latest exporter version and I have the same bug.

**Comment by PhysicsTeacher1** [comment] 2023-07-15 20:54
I'm Blender 3.3.6 and exporter 1.3.1 (July 5) and I still see what you see.  The latest exporter (1.3.1) is supposed to be used with Blender 3.3.x, and I still get what you see.  Going silent for a while to think this one over.  Hopefully Asobo will see the problem right away and fix it.

**Comment by PhysicsTeacher1** [comment] 2023-07-15 21:12
Found it!  Asobo, hope you're listening.
In previous versions of the file msfs_multi_export.py, the export function that picks up the settings in the Blender MultiExport/Settings panel simply set the 'use_selection' value to 'True'.  In the latest version, it's set to whatever you have the Limit To/Selection box set to.  So, as I see it, your "workaround" merely went back to the earlier settings when you checked Limit To/Selection.
I think I can see how this cascades down the line, but I'm 99% UNqualified to speak knowledgeably about Python code.  If they'd coded in in FORTRAN, I'd be more help.
Hope they can do something about this.  I'm in awe of what they've done so far.

**Comment by y-khodja** [comment] 2023-07-17 11:48
Hello!

Actually, the use only selected should be always set to true when you export glTF with the extension MSFS enabled. I will update the UI to make not editable when you enable the MSFS export. I have left it to the user in case you want to export a glTF dedicated to other software than the Sim.

**Comment by romandesign** [comment] 2023-07-17 15:50
Are you sure? That hardly makes any sense. The name of the checkbox implies that the objects need to be selected for export, which should not be the default, but even when selected this is not what happens, it exports all objects, which should be the default, with the exception of objects set as not renderable (a separate checkbox). Either it's named incorrectly and it means something else, or it's a bug. I suggest that if that option is required, name it something meaningful - because most people will check this off as exporting only the selected objects is not normally what we'd want, and anyway it's not what this checkbox seems to do...

**Comment by PhysicsTeacher1** [comment] 2023-07-17 19:30
Actually, she is correct.  I'll amplify in a minute.
Looking carefully at the code you will eventually see that the Khronos
exporter is able to export everything that's in every Scene and every
Collection of your Outliner.  That's what you saw without anything
checked.  However, that's not what we want; we want stuff that's in LOD
collections only to be exported (most of the time ???).  This is the way
the original (Vitus) exporter worked.  I remember the fix I made long ago
that allowed me to export all my LODs at once.  I used that for a long time.
So, how do we tell the Khronos exporter what is an LOD collection?  It
knows nothing about LODs.  We select each LOD collection one at a time,
call the Khronos exporter and come back and do it again for the next LOD
collection.  This selection process is done in the Multi-Exporter
automatically, so you should not have to select each one and export it one
at a time.  That panel with the Settings as checkboxes is really a copy of
the panel used in the Khronos exporter.  But, the Khronos exporter doesn't
know about LODs; that needs to be taken care of in the MSFS addon.  When
you export with the MSFS addon, that addon first deselects everything,
looks at all your collections, finds and makes a list of all the
collections with either 'x0' or '_LOD0' and so on, selects them one at a
time and calls the Khronos exporter for each one.  It is for this reason
that the checkbox Limit To Selected must be checked in the MSFS addon:
those checks and info are copied over to the Khronos panel (you don't see
this) and used to by it to decide what to export.
This way if you for some reason want to export something that is not
organized in an LOD collection, you can.  This is the most versatile way to
set up the panel.
However, I agree with making Limit To Selected the default so that it is
checked when you first see the Settings panel.  Having that panel available
is invaluable for me, because I organize my objects in Scenes and I use the
Limit To Active Scene almost all the time.  Having the other choices
available has also come in handy for me.  If all you're doing is exporting
one simple thing, you don't need all these controls, but your workload goes
way up when things get complex.
Sorry, this got a little wordy, but I'm satisfied with the answer.
I would encourage setting Limit To Selected to True by default in the MSFS
addon panel, though.
Good find, by the way.  Thanks.

**Comment by romandesign** [comment] 2023-07-18 14:14
OK, that works for me. Thanks for addressing the problem. There seems to be an emission factor not affecting the models issue, but it's a separate issue. I'll confirm that it's really there and will open  new issue about it.

**Comment by PhysicsTeacher1** [comment] 2023-07-18 16:56
I've always changed my installation code after I installed it.  The line
you need to change is in the folder 'com'.  The only Python code there is
mdfs_material_props.py.  You want to edit probably around line 113.  The
function reads: (If you're not comfortable changing source code, stop
reading right here!)

    bpy.types.Material.msfs_emissive_scale = bpy.props.FloatProperty(
        name="Emissive Scale",
        description="Controls the intensity of the emission. A value of 1.0
means that the material is fully emissive. This can be used in addition to
an emissive texture and in this case, it will control the emission Strenght
of this one.",
        min=0.0,
        max=100.0,
        default=Defaults.EmissiveScale,
        update=MSFS_Material_Property_Update.update_emissive_scale,
        options=set(),
    )

Note that I have changed the line to max=100.0 from the original of max=1.0
I have no idea where I that the max permitted in the sim is 100.

Save the file.  Close and re-open Blender and try it.

Please leave your request in place, since I think they should make that
change permanent.  Federico may agree with me.

I hope I'm sending this directly to you.  It doesn't need to be made
public, but that may not be what happens.

**Comment by romandesign** [comment] 2023-07-18 17:20
Thanks for the tip! Hmm... I look at that file and at line 117 it already says max=100.0
It makes sense, because as described in my issue I can set it up to 100 but it's ignored in the sim, because in the actual gtLF file it doesn't increase the actual emissive color values, but an extension value, which is apparently ignored by MSFS. The actual emissive color has to be set to more than RGB max of 1,0,0 for red as an example, to something like 30,0,0 for "glowing red". And it's not possible with the exporter AFAIK.

**Comment by romandesign** [comment] 2023-07-18 17:58
I tried playing with code in that section, but I couldn't make emissiveFactor go above 1,1,1, I think something is truncating it to  max 1. Unfortunately I need 30,0,0 for red glow etc.

**Comment by y-khodja** [comment] 2023-07-19 07:13
Hello,

Unfortunately the emissive value is exported by the Khronos exporter and for glTF convention it normalize its final value. I will try to add an extension to set a multiplier to be used by the sim for that ! 

Thank you for your report.

**Closed** 2023-09-21 12:41 UTC
